name: 'Android Instrumentation Test Runner'
description: 'GitHub Action for running Android Instrumentation tests'
author: 'ndtp'

inputs:

  app_apk:
    description: The full path to the application apk under test. For library projects, this will be the test apk.
    required: true

  app_package:
    description: The package name of the app. For example, `com.sample`
    required: true

  test_apk:
    description: The file name of the test runner .apk
    required: true

  test_package:
    description: The package name of test runner .apk
    required: true

  test_runner:
    description: The fully qualified class name for the Instrumentation test runner. e.g. `androidx.test.runner.AndroidJUnitRunner`
    required: true

  shard_count:
    description: "The total number of test execution shards to use."
    type: number
    default: 0
    required: false

  shard_index:
    description: "Current shard index to run for testing."
    type: number
    default: 0
    required: false

  annotation:
    description: Fully qualified name of the annotation to run.
    required: false

  not_annotation:
    description: Fully qualified name of the annotation to not run.
    required: false

  verbose:
    description: You can enable the verbose log for easier debugging.
    type: boolean
    default: false
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 21

    - name: Run tests
      shell: bash
      run: |
        "${{ github.action_path }}/action.sh" {{ inputs.app_apk }} ${{ inputs.app_package }} ${{ inputs.test_apk }} ${{ inputs.test_package }} ${{ inputs.test_runner }} ${{ inputs.shard_count }} ${{ inputs.shard_index }} ${{ inputs.annotation }} ${{ inputs.not_annotation }} ${{ inputs.verbose }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-test-results-${{ inputs.shard_index }}
        path: |
          android-test-logcat.log
          ./output/
          ./reports/*.xml

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Instrumentation Tests ${{ inputs.shard_index }}
        path: "./reports/*.xml"
        reporter: java-junit

branding:
  icon: 'check-circle'
  color: 'green'
